version: 2.1

executors:
  dandelion-executor:
    docker:
      - image: amsharifian/dandelion:micro

    working_directory: ~/dandelion

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SBT_ARGS: ""


commands:
  test-uir:
    description: "Run µIR tests"
    steps:
      - attach_workspace:
          at: ~/

      # Set environment
      - run: echo 'export PATH="/opt/verilator/verilator_4_016/bin:/opt/yosys/bin:$PATH"' >> $BASH_ENV

      # The -DminimalResources flag causes sbt to run tests sequentially,
      #  so we could actually use "sbt +test" to run all the crossVersioned tests.
      # We currently run them separately so we can run them in parallel.
      - run:
          command: |
            (cd uir-lib && cat /dev/null | sbt $SBT_ARGS compile)

jobs:
  build:
    executor: dandelion-executor

    steps:
      - checkout:
          path: uir-lib

      - run:
          command: |
            date > date.prep
            ls -al
            pwd
            (cd uir-lib && cat /dev/null | sbt $SBT_ARGS compile)

      - persist_to_workspace:
         root: /home/dandelion
         paths:
           - repo
           - .ivy2
           - .m2
           - .sbt





workflows:
  build_and_test:
    jobs:
      - build
