 version: 2.1
 jobs:
   build:
     docker:
       - image: amsharifian/dandelion
         user: "dandelion"
      
      working_directory: ~/repo

     steps:
       - checkout
       - run: echo "A first hello"
