version: 2.1

executors:
  dandelion-executor:
    docker:
      - image: amsharifian/dandelion
        user: "dandelion"

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SBT_ARGS: ""




jobs:
  build:
    executor: dandelion-executor

    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
